VERILOG_SOURCES = $(wildcard $(PWD)/../../**/*.v)
TOPLEVEL= channel_block
MODULE= channel_block
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
