VERILOG_SOURCES= ../channel_block.v ../../fully_associative_register/fully_associative_register.v \
../../ram/ram_controller.v ../../adc_block/adc_block.v ../../adc_interface/adc_interface.v\
../../moving_average/moving_average.v
TOPLEVEL= channel_block
MODULE= channel_block
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
