VERILOG_SOURCES = $(PWD)/../adc_block.v $(PWD)/../../adc_interface/adc_interface.v $(PWD)/../../moving_average/moving_average.v
TOPLEVEL= adc_block
MODULE= adc_block_test
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
