VERILOG_SOURCES =$(wildcard $(PWD)/../../**/*.v)# $(wildcard $(PWD)/../*.v)
TOPLEVEL= adc_block
MODULE= adc_block_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
