VERILOG_SOURCES =$(wildcard $(PWD)/../../**/*.v)
TOPLEVEL= adc_block
MODULE= adc_block_test
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
