VERILOG_SOURCES = $(PWD)/../i2c_master_write_only.v
TOPLEVEL= i2c_alt
MODULE= i2c_master_write_only
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
