VERILOG_SOURCES = $(PWD)/../ft245.v $(PWD)/../test_block_io/SB_IO.v $(PWD)/../ft245_block.v
TOPLEVEL= ft245_block
MODULE= ft245_block
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
