VERILOG_SOURCES = $(wildcard $(PWD)/../../**/*.v)
TOPLEVEL= conf_regs
MODULE= conf_regs
EXTRA_ARGS= -I../../../inc/		# Add to includes path the parent dir
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
