VERILOG_SOURCES = $(PWD)/../configuration_registers_rx.v
TOPLEVEL= configuration_registers_rx
MODULE= configuration_registers_rx_test
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
