VERILOG_SOURCES = $(PWD)/../fully_associative_register.v
TOPLEVEL= fully_associative_register
MODULE= fully_associative_register
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
