VERILOG_SOURCES = ../trigger_block.v ../../fully_associative_register/fully_associative_register.v \
../../buffer_controller/buffer_controller.v	../../trigger_input_selector/trigger_input_selector.v \
../../buffer_controller/edge_detector.v
TOPLEVEL= trigger_block
MODULE= trigger_block
EXTRA_ARGS = -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
