VERILOG_SOURCES =$(wildcard $(PWD)/../../**/*.v)
#VERILOG_SOURCES =$(PWD)/../trigger_block.v $(PWD)/../../buffer_controller/buffer_controller.v $(PWD)/../../fully_associative_register/fully_associative_register.v $(PWD)/../../trigger_input_selector/trigger_input_selector.v
# $(PWD)/../trigger_block.v
# $(PWD)/../../buffer_controller/buffer_controller.v
# $(PWD)/../../fully_associative_register/fully_associative_register.v
# $(PWD)/../../trigger_input_selector/trigger_input_selector.v
# $(PWD)/../../
TOPLEVEL= trigger_block
MODULE= trigger_block
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
