VERILOG_SOURCES = $(PWD)/../moving_average.v
TOPLEVEL= moving_average
MODULE= moving_average
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
