VERILOG_SOURCES = $(PWD)/../ram_controller.v
TOPLEVEL= ram_controller
MODULE= ram_controller
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
