VERILOG_SOURCES = $(PWD)/../SB_RAM512x8.v $(PWD)/../ram_interface_2.v
TOPLEVEL= ram_interface_2
MODULE= ram_controller
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
