VERILOG_SOURCES = $(PWD)/../ft245.v $(PWD)/SB_IO.v_ $(PWD)/SB_PLL40_CORE.v_ $(PWD)/tx_rx.v
TOPLEVEL=tx_rx
MODULE= tx_rx
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
