VERILOG_SOURCES = $(PWD)/../conf_shift_register.v
TOPLEVEL= conf_shift_register
MODULE= conf_shift_register
EXTRA_ARGS= -I../../../inc/		# Add to includes path the parent dir
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
