VERILOG_SOURCES = $(PWD)/../sdram_controller.v
TOPLEVEL= sdram_controller
MODULE= sdram_controller
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
