VERILOG_SOURCES = $(PWD)/../adc_interface.v
TOPLEVEL= adc_interface
MODULE= adc_interface_test
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
