VERILOG_SOURCES = ../registers_rx_block.v ../../configuration_registers_rx/configuration_registers_rx.v \
../../requests_handler/requests_handler.v
TOPLEVEL= registers_rx_block
MODULE= registers_rx_block
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
