VERILOG_SOURCES = $(PWD)/../../configuration_registers_rx/configuration_registers_rx.v $(PWD)/../../fully_associative_register/fully_associative_register.v $(PWD)/../../requests_handler/requests_handler.v $(PWD)/../registers_rx_block.v
TOPLEVEL= registers_rx_block
MODULE= registers_rx_block
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
