VERILOG_SOURCES = $(PWD)/../../ft245.v $(PWD)/ft245_block.v $(PWD)/../../../test_modules/SB_IO.v
TOPLEVEL=ft245_block
MODULE= ft245_block
EXTRA_ARGS= -I../../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
