VERILOG_SOURCES = $(PWD)/tx_rx.v $(PWD)/../../../test_modules/SB_PLL40_CORE.v $(PWD)/../../uart.v
TOPLEVEL=tx_rx
MODULE=tx_rx
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
