VERILOG_SOURCES :=  $(wildcard $(PWD)/../../modules/**/*.v) $(wildcard $(PWD)/../*.v)
TOPLEVEL= top_level_ft245
MODULE= top_level_ft245
EXTRA_ARGS= -I../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
