VERILOG_SOURCES = $(PWD)/../edge_detector.v
TOPLEVEL= edge_detector
MODULE= edge_detector_test
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
