VERILOG_SOURCES =$(wildcard $(PWD)/../../**/*.v) $(wildcard $(PWD)/../../**/**/*.v)
#$(wildcard $(PWD)/*.v)
TOPLEVEL= top_level
MODULE= top_level
EXTRA_ARGS= -I../../../inc/
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
