VERILOG_SOURCES = $(PWD)/../edge_detector.v $(PWD)/../buffer_controller.v
TOPLEVEL= buffer_controller
MODULE= buffer_controller_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
